language: cpp
compiler: gcc
before_install: sudo add-apt-repository -y ppa:yubico/stable && sudo apt-get update
install: sudo apt-get install build-essential libqt4-dev libgcrypt11-dev zlib1g-dev libxtst-dev libykpers-1-dev libyubikey-dev
before_script: mkdir build && pushd build
script: cmake .. && make && make test
